export const BRANDING = {
  shield: require("../../assets/branding/condoflow-shield.png"),
  wordmark: require("../../assets/branding/condoflow-wordmark.png"),
  logoTransparent: require("../../assets/branding/condoflow-logo-transparent.png"),
  logoWithBackground: require("../../assets/branding/condoflow-logo-bg.png"),
} as const;

// CondoFlow core palette and semantic tokens for consistent UI styling.
export const BRAND_COLORS = {
  primary: "#0C4EA6",
  primaryDark: "#0A2F74",
  primaryLight: "#2F79B3",
  accent: "#12D7E6",
  accentSoft: "#8FE7DF",
  accentDark: "#00C2E0",
  whiteOverlay: "rgba(255,255,255,0.14)",
  info: "#1D4ED8",
  infoSoft: "#71B0F4",
  success: "#067647",
  successBright: "#00F05A",
  warning: "#B45309",
  danger: "#B42318",
  badgeRed: "#FF0000",
  purple: "#7C3AED",
  pending: "#F59E0B",
  background: "#F4F6F8",
  backgroundSoft: "#EEF2F6",
  backgroundMuted: "#ECECED",
  surface: "#FFFFFF",
  surfaceSoft: "#EAF2FF",
  border: "#D9DDE3",
  borderSoft: "#EDF1F6",
  text: "#0F172A",
  textStrong: "#101828",
  mutedText: "#516179",
  textSubtle: "#667085",
  textOnPrimary: "#FFFFFF",
  white: "#FFFFFF",
} as const;
